# Name of your workflow.
name: main

on: [close]

env:
  NODE_VERSION: 18.12.1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Without quotation
        uses: actions/setup-node@v4.0.2

      - name: With single quotation
        uses: 'actions/setup-node@v3.0.0'

      - name: With double quotation
        uses: "actions/setup-node@v3.0.0"
