name: GitHub Actions Version Updater Demo

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          token: ${{ secrets.WORKFLOW_SECRET }}
      - uses: kenz/github-actions-version-updater@v0.8.2beta
        with:
          token: ${{ secrets.WORKFLOW_SECRET }}
